[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube-coreum"
repository = "https://github.com/CoreumFoundation/test-tube"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
cosmrs = {version = "0.15.0", features = ["cosmwasm", "rpc"]}
cosmwasm-std = {version = "1.5.4", features = ["stargate"]}
tendermint-proto = "0.33.1"
prost = "0.12.4"
serde = "1.0.198"
serde_json = "1.0.117"
thiserror = "1.0.60"

[dev-dependencies]
cw1-whitelist = "1.1.1"
rayon = "1.7.0"
