[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube-coreum"
repository = "https://github.com/CoreumFoundation/test-tube"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.20.0"
cosmrs = {version = "0.14.0", features = ["cosmwasm", "rpc"]}
cosmwasm-std = {version = "1.4.0", features = ["stargate"]}
tendermint-proto = "0.33.1"
prost = "0.11.0"
serde = "1.0.188"
serde_json = "1.0.106"
thiserror = "1.0.48"

[dev-dependencies]
cw1-whitelist = "1.1.0"
rayon = "1.7.0"
